In [41]:
import pickle
import numpy as np
import pandas as pd

In [42]:
clf=pickle.load(open('models/clf.pkl','rb'))
ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl','rb'))

In [43]:

Pclass = 2
Sex = 'male'
age = 31.0
SibSp = 0
Parch = 0
Fare = 10.5
Embarked = 'S'

test_input = pd.DataFrame([[Pclass,Sex,age,SibSp,Parch,Fare,Embarked]],columns=['Pclass','Sex','Age','SibSp','Parch','Fare','Embarked'])
test_input

Pclass   Sex   Age  SibSp  Parch  Fare Embarked
0       2  male  31.0      0      0  10.5        S

In [44]:
# array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)
# array([2, 'male', 31.0, 0, 0, 10.5, 'S'], dtype=object)
test_input_sex = ohe_sex.transform(test_input[['Sex']])
test_input_embarked = ohe_embarked.transform(test_input[['Embarked']])
test_input_sex,test_input_embarked
# ['Pclass', 'SibSp', 'Parch', 'Fare','Age','Sex','Embarked']  -> order to give input to model

/home/janardhan/anaconda3/lib/python3.11/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but OneHotEncoder was fitted without feature names
  warnings.warn(


(array([[1]]), array([[0, 1]]))

In [45]:
test_input = np.concatenate([test_input.drop(['Sex','Age','Embarked'],axis=1).values,[test_input['Age']],test_input_sex,test_input_embarked],axis=1)
test_input

array([[ 2. ,  0. ,  0. , 10.5, 31. ,  1. ,  0. ,  1. ]])

In [46]:
clf.predict(test_input)
# survived

array([1])