In [2]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_diabetes

In [3]:
x,y = load_diabetes(return_X_y=True)

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=4)

In [5]:
x_train.shape,x_test.shape

((353, 10), (89, 10))

### by SGDRegressor

In [9]:
from sklearn.linear_model import SGDRegressor,Ridge
sgd = SGDRegressor(penalty='l2',alpha=0.001,max_iter=500,learning_rate='constant',eta0=0.1)
# alpha -> lambda -> ridge
# penalty -> ridge
# max_iter -> epoch
# eta0 -> learning_rate
sgd.fit(x_train,y_train)

SGDRegressor(alpha=0.001, eta0=0.1, learning_rate='constant', max_iter=500)

In [10]:
sgd.intercept_,sgd.coef_

(array([167.15662961]),
 array([  48.83121665, -157.13398232,  366.01950517,  266.87578505,
          -5.05393846,  -55.91124824, -168.74785432,  137.00035967,
         328.12781434,   97.18659652]))

In [11]:
from sklearn.metrics import r2_score
y_pred = sgd.predict(x_test)
r2_score(y_test,y_pred)

0.4382258892084202

### By ridge regression

In [14]:
ridge = Ridge(alpha=0.001,solver='sparse_cg')
ridge.fit(x_train,y_train)
# sparse_cg -> uses gradient descent for training the model

Ridge(alpha=0.001, solver='sparse_cg')

In [15]:
y_pred = ridge.predict(x_test)
r2_score(y_test,y_pred)

0.4625010162027918

In [16]:
ridge.intercept_,ridge.coef_

(151.101985182554,
 array([  34.52192778, -290.84083871,  482.40181675,  368.06786931,
        -852.44872818,  501.59160694,  180.11115474,  270.76334443,
         759.73534802,   37.49135796]))

In [34]:
class MeraRidge:
    def __init__(self,alpha,learning_rate,epochs):
        self.alpha = alpha
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.intercept_ = None
        self.coef_ = None
    def fit(self,x_train,y_train):
        self.coef_ = np.ones(x_train.shape[1])
        self.intercept_ = 0
        theta = np.insert(self.coef_,0,self.intercept_)

        x_train = np.insert(x_train,0,1,axis=1)

        for i in range(self.epochs):
            theta_der = np.dot(x_train.T,x_train).dot(theta)-np.dot(x_train.T,y_train)+self.alpha*theta
            theta = theta - self.learning_rate*theta_der
            # print(theta)
        self.coef_ = theta[1:]
        self.intercept_ = theta[0]
        # print(self.intercept_)
        # print(self.coef_)

    def predict(self,x_test):
        return np.dot(x_test,self.coef_)+self.intercept_

In [35]:
ridge_gd = MeraRidge(alpha=0.001,learning_rate=0.005,epochs=500)
ridge_gd.fit(x_train,y_train)
# if learning rate == 0.1 -> the values goes to inf than got NaN why?

In [36]:
y_pred = ridge_gd.predict(x_test)


In [38]:
r2_score(y_pred,y_test)

-0.2259659986493514