In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_diabetes
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
x,y = load_diabetes(return_X_y=True)

In [3]:
x.shape

(442, 10)

In [4]:
y.shape

(442,)

In [5]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=2)
x_train.shape,x_test.shape

((331, 10), (111, 10))

In [6]:
y_train.shape,y_test.shape

((331,), (111,))

In [7]:
lr = LinearRegression()
lr.fit(x_train,y_train)
lr.coef_,lr.intercept_

(array([ -36.49034836, -194.09811575,  513.88593284,  355.02971098,
        -891.00370348,  591.68794911,  155.49417805,  146.44668444,
         846.85202529,   54.30219759]),
 152.65886927494057)

In [8]:
y_pred = lr.predict(x_test)
r2_score(y_test,y_pred)

0.4429562235529032

In [16]:
class GDRegressor:
    def __init__(self,learning_rate,epochs):
        self.coef_ = None
        self.intercept_ = None
        self.learning_rate = learning_rate
        self.epochs = epochs

    def fit(self,x,y):
        self.coef_ = np.ones(x.shape[1])
        self.intercept_ = 0
        
        for i in range(self.epochs):
            # vectorizationw
            y_hat = self.intercept_ + np.dot(x,self.coef_)
            intercept_der = -2*np.mean(y-y_hat)
            self.intercept_ = self.intercept_ - self.learning_rate * intercept_der

            coef_der = -2 * np.dot((y - y_hat),x)/x.shape[0]
            # if i==0:
            # FOR UNDERSTANDING
            #     print((y - y_hat).shape)
            #     print(x.shape)
            #     print(np.dot((y - y_hat),x))
            self.coef_ = self.coef_ - self.learning_rate*coef_der
    def predict(self,x):
        return np.dot(x,self.coef_)+self.intercept_

In [56]:
gdr = GDRegressor(epochs=1000,learning_rate=0.01)

In [57]:
import time
start = time.time()
gdr.fit(x_train,y_train)
print("The time taken : ",time.time()-start)

The time taken :  0.0769810676574707


In [58]:
y_pred = gdr.predict(x_test)

In [59]:
r2_score(y_test,y_pred)

0.10792836892679036

In [60]:
gdr.intercept_

151.48038495127116

In [61]:
gdr.coef_

array([ 16.12544306,   4.1959078 ,  42.01896851,  33.60253244,
        15.93523872,  12.65609978, -25.65367345,  29.27258245,
        42.25326365,  27.22824941])

In [42]:
a = np.array([[1,1,1,1,1]])
b = np.array([[1]])
np.dot(b,a).shape
# b.shape

(1, 5)

In [43]:
a = np.array([1,2,3])
b = np.array([[1,2,3],[1,2,3]])
np.dot(b,a)

array([14, 14])

In [44]:
# check second param as 1d or not
# if 1d no cols in a == no cols in b
#     a row in b is multiplied with each row in a
# else (2d and 2d ) now cols in a == no rows in b
#     first row with first col .......

### by SGDRegressor in sklearn

In [66]:
from sklearn.linear_model import SGDRegressor
reg = SGDRegressor(max_iter=100,learning_rate='constant',eta0=0.01)
# eta is the learning rate

In [67]:
reg.fit(x_train,y_train)

/home/janardhan/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_stochastic_gradient.py:1575: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(


SGDRegressor(learning_rate='constant', max_iter=100)

In [68]:
y_pred = reg.predict(x_test)

In [69]:
r2_score(y_pred,y_test)

-0.5591515547975534